import type { Metadata } from "next";
import { Exo_2, Lora } from "next/font/google";
import "./globals.css";

const exo = Exo_2({
  variable: "--font-exo-sans",
  subsets: ["latin"],
});

const lora = Lora({
  variable: "--font-lora-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.variable} ${lora.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}

      </body>
    </html>
  );
}
